### ISSUE TITLE
HIE (commit 7c206d) crashes unexpectedly

### ISSUE THREAD

**Issue by jneira** [mpickering/haskell-ide-engine#64]
Testing latest commit ([7c206d](https://github.com/mpickering/haskell-ide-engine/commit/7c206de70cc474ac0dbe0666b9713ab0e47d9d57)) of the hie-bios branch i've detected that hie crashes without no previous error. Behaviour:
* When open vscode the progress of `Initializating cradle` doesnt finish
* The last log line is:
```
019-11-21 19:19:47.3299622 [ThreadId 53] - Modules in the cradle: ["lib\\CabalTestLib.hs"]
```
* Then when i do a hover in the file opened:
```
[Info  - 10:20:24] Connection to server got closed. Server will restart.
[Error - 10:20:24] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\user\.vscode\extensions\alanz.vscode-hie-server-0.0.31\dist\extension.js:1:36201)
	at Object.dispose (c:\Users\user\.vscode\extensions\alanz.vscode-hie-server-0.0.31\dist\extension.js:1:90254)
	at D.handleConnectionClosed (c:\Users\user\.vscode\extensions\alanz.vscode-hie-server-0.0.31\dist\extension.js:1:90429)
	at D.handleConnectionClosed (c:\Users\user\.vscode\extensions\alanz.vscode-hie-server-0.0.31\dist\extension.js:157:34664)
	at t (c:\Users\user\.vscode\extensions\alanz.vscode-hie-server-0.0.31\dist\extension.js:1:88578)
	at invoke (c:\Users\user\.vscode\extensions\alanz.vscode-hie-server-0.0.31\dist\extension.js:1:230177)
	at n.fire (c:\Users\user\.vscode\extensions\alanz.vscode-hie-server-0.0.31\dist\extension.js:1:230907)
	at $ (c:\Users\user\.vscode\extensions\alanz.vscode-hie-server-0.0.31\dist\extension.js:1:28132)
	at invoke (c:\Users\user\.vscode\extensions\alanz.vscode-hie-server-0.0.31\dist\extension.js:1:230177)
	at n.fire (c:\Users\user\.vscode\extensions\alanz.vscode-hie-server-0.0.31\dist\extension.js:1:230907)
	at l.fireClose (c:\Users\user\.vscode\extensions\alanz.vscode-hie-server-0.0.31\dist\extension.js:1:249715)
	at Socket.<anonymous> (c:\Users\user\.vscode\extensions\alanz.vscode-hie-server-0.0.31\dist\extension.js:1:250472)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 10:20:24] Request textDocument/hover failed.
```
* I observe that the hie process is restarted
* There is no error in the log between them. Full log here: https://gist.github.com/jneira/aa9665715b357580d2498e454ca5dea8#file-vscode-7c206d-ko-output
* HIE configures again the file after the restart and the behaviour repeats indefinitely
* Full log of a succesful session using the same project/file/system with [924de7](https://github.com/mpickering/haskell-ide-engine/commit/924de7c5b45e1aa4e5150cdcc5d04e454b9192a2): https://gist.github.com/jneira/aa9665715b357580d2498e454ca5dea8#file-vscode-924de7-ok-output
* Maybe is windows specific

**Comment by jneira** [comment]
I'v test the branch with the las changes: 41b9cab and the error persist.
However at least i've got an error about vfs just after i do the hover and before the restart:
```
hie.exe: File not found in VFS: NormalizedUri "file:///D:/ws/haskell/cabal-test/lib/CabalTestLib.hs"VFS {vfsMap = fromList [(NormalizedUri "file:///d:/ws/haskell/cabal-test/lib/CabalTestLib.hs",VirtualFile {_version = 1, _text = Rope {unrope = Fork Leaf "{-# LANGUAGE OverloadedStrings #-}\r\nmodule CabalTestLib where\r\n\r\nimport Network.HTTP.Types.URI\r\nimport qualified Data.ByteString.Char8 as BS\r\n\r\nurlEncoded :: BS.ByteString\r\nurlEncoded = BS.pack \"Hi\"" Leaf (Position {codeUnits = 198, rowColumn = RowColumn {row = 7, column = 25}})}})], vfsTempDir = "C:\\TEMP\\haskell-lsp8796"}
``` 

`C:\\TEMP\\haskell-lsp8796` is a directory and it exists but is is empty

Maybe related with #36

**Comment by jneira** [comment]
I've tested hie with the changes to uri normalization and the error is gone. Now the crash doesnt reproduce butthe execution seems to hang (showing Initializating cradle in the info bar indefinitely)

**Comment by jneira** [comment]
Hi, i've tried #67 with no luck, same behavior than previous test: hie doesnt crash but it get stuck in `Initializating cradle:module` 😟 
I dont see errors in the log but it is [here](https://gist.github.com/jneira/4911d36d50f174fe7946eda4395135c1)

**Comment by mpickering** [comment]
Does this happen with every example you try? The log looks fine.. does hover work?

**Comment by jneira** [comment]
After some tests combining `persist-virtual-file` and make [the fix of uri keys](https://github.com/alanz/haskell-lsp/pull/205) work:
* only `persist-virtual-file`: ko (crash in win 7 or hang in win 10)
* only fixing the key: ok
* both: ok

So being  `persist-virtual-file` an improvement in its own it seems doesnt fix the crash/hang in windows. I am assuming that in linux it is not reproduced.

I'll try to trace the cause, restoring the version that triggers the crash.

**Comment by jneira** [comment]
> Does this happen with every example you try? The log looks fine.. does hover work?

Nope, the behaviour is similar to the dhall case (#32) for win 10. 
I was confused cause the behaviour was different between win 7 (always crash) and win 10 (always get stuck)

**Comment by jneira** [comment]
I've double checked the differente versions and in win 7:
* only persist-virtual-file: ok
* only fixing the key: ok

So maybe i did dome error switching git versions or setting the correct executable in vscode :worried: 

However in win 10 the execution hangs with versions that works in win 7. I'll try to get the same results in both.

**Comment by jneira** [comment]
At last i've been able to test in windows 10 and the results are the same. I've traced the VFS lookups:

* hie hie-bios head + haskell lsp driverup
```
2019-11-30 18:19:50.8569891 [ThreadId 48] - persistVirtualFile': uri: Uri {getUri = "file:///D:/dev/ws/haskell/cabal-test/src/Lib.hs"}
2019-11-30 18:19:50.8699821 [ThreadId 48] - persistVirtualFile': fp: "C:\\TEMP\\haskell-lsp9408\\-870452232-1.hs"

2019-11-30 18:19:51.0768542 [ThreadId 8] - persistVirtualFile': uri: Uri {getUri = "file:///d%3A/dev/ws/haskell/cabal-test/src/Lib.hs"}
2019-11-30 18:19:51.0778558 [ThreadId 8] - persistVirtualFile': fp: "C:\\TEMP\\haskell-lsp9408\\-870452232-1.hs"
```
* hie-bios master
```
2019-11-30 18:41:17.775639 [ThreadId 49] - persistVirtualFile': uri: Uri {getUri = "file:///D:/dev/ws/haskell/cabal-test/src/Lib.hs"}
```
   no more calls to persistVirtualFile cause hie crashes

* hie persist-virtual-file

```
2019-11-30 22:20:45.7803192 [ThreadId 51] - persistVirtualFile': uri: Uri {getUri = "file:///D:/dev/ws/haskell/cabal-test/src/Lib.hs"}
2019-11-30 22:20:45.7803192 [ThreadId 51] - persistVirtualFile': fp: Nothing

2019-11-30 22:20:45.7833189 [ThreadId 8] - persistVirtualFile': uri: Uri {getUri = "file:///d%3A/dev/ws/haskell/cabal-test/src/Lib.hs"}
2019-11-30 22:20:45.793315 [ThreadId 8] - persistVirtualFile': fp: Just "C:\\TEMP\\haskell-lsp1384\\1871409432-0-Lib.hs.hs"
```

* hie persist-virtual-file + haskell lsp driverup

```
2019-11-30 22:34:40.9906942 [ThreadId 48] - persistVirtualFile': uri: Uri {getUri = "file:///D:/dev/ws/haskell/cabal-test/src/Lib.hs"}
2019-11-30 22:34:41.0036856 [ThreadId 48] - persistVirtualFile': fp: Just "C:\\TEMP\\haskell-lsp12804\\-870452232-0-Lib.hs.hs"

2019-11-30 22:34:41.159591 [ThreadId 8] - persistVirtualFile': uri: Uri {getUri = "file:///d%3A/dev/ws/haskell/cabal-test/src/Lib.hs"}
2019-11-30 22:34:41.1605903 [ThreadId 8] - persistVirtualFile': fp: Just "C:\\TEMP\\haskell-lsp12804\\-870452232-0-Lib.hs.hs"
```
with driverup we get hlint diagnostics in windows 10 and no more `lintCmd: no access to the persisted file.`!
